In [26]:
import numpy as np

print("hello world")

hello world


In [27]:
import numpy as np
a= np.array([20,30,40])
b= np.array([6,2,4])
print(a*b)
print(a)
print(b)


[120  60 160]
[20 30 40]
[6 2 4]


In [28]:
l1  = [10,12,23,5]
l2 = 2
print(l1*l2)


[10, 12, 23, 5, 10, 12, 23, 5]


In [29]:
a= np.array([2,3,"9"])
print(a)

['2' '3' '9']


In [30]:
a= np.array([2,3,5.2])
print(a)

[2.  3.  5.2]


In [31]:
a = np.array(([20,30,10],[40,50,60]))
print(a)

[[20 30 10]
 [40 50 60]]


In [32]:
a = np.array([[10,20,30],[40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [34]:
l1 = [[10,12],[23,5,33]]
print(l1)


[[10, 12], [23, 5, 33]]


In [ ]:
print