In [50]:
import numpy as np
#single dimensional array
arr = np.array([10,20,30,40])
print(arr)
print((arr[0:2]))
print((arr[2:]))
print(type(arr))
# multi dimensional arrray
arr1 = np.array([[1,2,3,10],[4,5,6,20],[7,8,9,30]])
print(arr1)
print(arr1[0:2,0:3])
print(arr1[1,2:])
print(arr1[2,1:3])
print(np.shape(arr1))  #row/col
print(np.size(arr1))   # number of element
print(np.ndim(arr1))   # dimension (row and col)
print(np.dtype)        # data type of array
print(len(arr1))        # number of nested value
print(arr1.astype(float))  #conversion of datatype

[10 20 30 40]
[10 20]
[30 40]
<class 'numpy.ndarray'>
[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]
[[1 2 3]
 [4 5 6]]
[ 6 20]
[8 9]
(3, 4)
12
2
<class 'numpy.dtype'>
3
[[ 1.  2.  3. 10.]
 [ 4.  5.  6. 20.]
 [ 7.  8.  9. 30.]]


In [56]:

# append function
import numpy as np
a= np.array([[10,20],[30,40]])
print(np.append(a,50))
print(np.append(a,[80,588]))

[10 20 30 40 50]
[ 10  20  30  40  80 588]
[10 45 20 30 40]
[[ 10  20  90]
 [ 30  40 100]]
[[10 20]
 [90 90]
 [30 40]]
[[10 20]
 [90 90]
 [30 40]
 [90 90]]


In [47]:
# insert function
print(np.insert(a,1,45))
print(np.insert(a,2,[90,100],axis = 1))
print(np.insert(a,1,[90],axis = 0))
print(np.insert(a,[1,2],[90],axis = 0))

[10 45 20 30 40]
[[ 10  20  90]
 [ 30  40 100]]
[[10 20]
 [90 90]
 [30 40]]
[[10 20]
 [90 90]
 [30 40]
 [90 90]]


In [70]:
# delete function
print(a)
print()
print(np.delete(a,1,axis = 0))
print()
print(np.delete(a,1,axis = 1))


[[10 55 77 20]
 [30 40 44 11]]

[[10 55 77 20]]

[[10 77 20]
 [30 44 11]]


In [73]:
a= np.array([[10,55,77,20],[30,40,44,11]])
print(np.delete(a,1,axis=0))
print()
print(np.delete(a,1,axis=1))


[[10 55 77 20]]

[[10 77 20]
 [30 44 11]]


In [74]:
# sort function
b = np.array([[1,5,3,69],[4,690,11,37]])
print(np.sort(b))

[[  1   3   5  69]
 [  4  11  37 690]]


In [79]:

# for searching 
b = np.array([1,5,3,69,55])
s= np.where(b == 3)
s1= np.where(b%2==0)
print(s)
print()
print(s1)


(array([2], dtype=int64),)

(array([], dtype=int64),)


In [87]:
# search sort
ar = np.array([1,2,3,4,5])
ss= np.searchsorted(ar,3)
print(ss)
ss= np.searchsorted(ar,5)
print(ss)

2
4


In [89]:
# filter 
c= np.array([20,30,40,50,60])
fa = c>35
new = c[fa]
print(new)

[40 50 60]


In [90]:
fa = [True,False,True,False,True]
new = c[fa]
print(new)

[20 40 60]


In [94]:
# aggregating function
c= np.array([20,30,40,50,60])
print(np.sum(c))
print(np.min(c))
print(np.max(c))
print(np.size(c))
print(np.mean(c))
print(np.cumsum(c))
print(np.cumprod(c))


200
20
60
5
40.0
[ 20  50  90 140 200]
[      20      600    24000  1200000 72000000]


In [100]:
#  important - sum(),prod(),cumsum(),cumprod()
x= np.array([10,50,100,150,300,350])
y= np.array([10,50,20,60,30,10])
price=np.array(x)
quantity=np.array(y)
print()
print(price,"\n",quantity)
d= np.cumprod([price,quantity],axis = 0)
print(d[1].sum())
print(d[0].sum())



[ 10  50 100 150 300 350] 
 [10 50 20 60 30 10]
26100
960


In [110]:
import statistics as stats
x= ([10,50,100,150,300,100,350])
# y = np.array(a)
print(np.mean(x))
print(np.median(x))
print(stats.mode(x))
print(np.std(x))
print(np.var(x))

151.42857142857142
100.0
100
117.76836483157113
13869.387755102041


In [112]:
# statistical function
# -1 represent invesly proportional relationbship
#  1 represent proportional relationbship
# 0 represent no relationbship
tobacco_consumption= ([10,50,100,150,300,350])
death= ([10,50,20,60,30,10])
print(np.corrcoef([tobacco_consumption,death]))

[[ 1.        -0.1877537]
 [-0.1877537  1.       ]]


In [113]:
price = [300,100,350,150,200]
sales  =[10,20,7,17,3]
print(np.corrcoef([price,sales]))


[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
